[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/downloads
Session\ExcludedFileNames=
Session\GlobalMaxRatio=2
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=33742
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/temp

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\Auth\Enabled=false
WebUI\Auth\SubnetWhitelist=0.0.0.0/0
WebUI\Auth\SubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=0.0.0.0/0
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\HttpOnlyCookie=false
WebUI\LocalHostAuth=false
WebUI\ReverseProxySupportEnabled=true
WebUI\SecureCookie=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
